apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.user | quote }}
  admin-password: {{ .Values.admin.password | quote }}
