[workspace]
resolver = "3"
members = ["crates/*", "services/*"]

[workspace.package]
edition = "2024"
license = "UNLICENSED"
version = "0.1.0"

[patch.crates-io]
egui-wgpu = { path = "crates/egui-wgpu" }
