[package]
name = "c2-observability"
version = "0.1.0"
edition = "2024"

[dependencies]
metrics = "0.24.3"
metrics-exporter-prometheus = "0.18.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
