[package]
name = "c2-proto"
edition.workspace = true
license.workspace = true
version.workspace = true
build = "build.rs"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"
protoc-bin-vendored = "3.2.0"
