apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c2-dev
  namespace: argocd
spec:
  project: c2
  source:
    repoURL: https://github.com/ASoldo/c2_ri
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: c2-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
