apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c2-ingress
  namespace: c2-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: c2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: c2-gateway
                port:
                  number: 8080
    - host: grafana.c2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: c2-grafana
                port:
                  number: 3000
    - host: prometheus.c2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: c2-prometheus
                port:
                  number: 9090
