apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - n8n-ollama-postgres.yaml
  - surrealdb.yaml

patchesStrategicMerge:
  - c2cluster-patch.yaml
  - operator-patch.yaml
  - service-nodeport-patch.yaml
