apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - surrealdb.yaml

patchesStrategicMerge:
  - c2cluster-patch.yaml
  - operator-patch.yaml
  - service-nodeport-patch.yaml

secretGenerator:
  - name: c2-web-weather
    envs:
      - c2-web-weather.env
    options:
      disableNameSuffixHash: true
