apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2-operator
  namespace: c2-system
spec:
  template:
    spec:
      containers:
        - name: c2-operator
          image: harbor.c2.local/c2/c2-operator:dev
          imagePullPolicy: Always
          env:
            - name: C2_ENV
              value: dev
